#! Local use only
version: "3.8"

services:

  api:
    build: ./backend
    container_name: api
    restart: always
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/local.env
  
  front:
    build: ./frontend
    container_name: front
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/local.env
  
  pgsql:
    image: postgres:13-alpine
    container_name: pgsql
    env_file:
      - db.env
    volumes:
      - .database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass password
    ports:
     - "6379:6379"